--Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
----------------------------------------------------------------------------------
--Tool Version: Vivado v.2018.2 (win64) Build 2258646 Thu Jun 14 20:03:12 MDT 2018
--Date        : Mon Apr 25 22:46:19 2022
--Host        : Supintmac running 64-bit major release  (build 9200)
--Command     : generate_target AXI_interconnect.bd
--Design      : AXI_interconnect
--Purpose     : IP block netlist
----------------------------------------------------------------------------------
